/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class blue_stack_sqlite_SQLiteDatabase */

#ifndef _Included_blue_stack_sqlite_SQLiteDatabase
#define _Included_blue_stack_sqlite_SQLiteDatabase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     blue_stack_sqlite_SQLiteDatabase
 * Method:    opendb
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_blue_stack_sqlite_SQLiteDatabase_opendb
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     blue_stack_sqlite_SQLiteDatabase
 * Method:    closedb
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_blue_stack_sqlite_SQLiteDatabase_closedb
  (JNIEnv *, jobject, jint);

/*
 * Class:     blue_stack_sqlite_SQLiteDatabase
 * Method:    beginTransaction
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_blue_stack_sqlite_SQLiteDatabase_beginTransaction
  (JNIEnv *, jobject, jint);

/*
 * Class:     blue_stack_sqlite_SQLiteDatabase
 * Method:    commitTransaction
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_blue_stack_sqlite_SQLiteDatabase_commitTransaction
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
